server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.115.177.122:3317/rule?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
logging:
  config: classpath:logback-spring.xml
