server:
  port: 8084
  servlet:
    context-path: /demo

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://47.115.177.122:3317/sys?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
logging:
  config: classpath:logback-spring.xml
